=== projeduc/intro_apprentissage_automatique/data/adult.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT income (candidat)*>
<!ATTLIST candidat id CDATA #REQUIRED>
<!ELEMENT candidat (age?, workclass?, education?, marital-status?, sex?, hours-per-week?, class)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT workclass (#PCDATA)>
<!ELEMENT education (#PCDATA)>
<!ELEMENT marital-status (#PCDATA)>
<!ELEMENT sex (#PCDATA)>
<!ELEMENT hours-per-week (#PCDATA)>
<!ELEMENT class (#PCDATA)>

=== projeduc/intro_apprentissage_automatique/data/adult4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE income SYSTEM "adult.dtd">
<income>
<candidat id="52">
    <age>47</age>
    <workclass>Local-gov</workclass>
    <education>Some-college</education>
    <marital-status>divorced</marital-status>
    <sex>F</sex>
    <hours-per-week>38</hours-per-week>
    <class>N</class>
</candidat>

<candidat id="53">
    <age>34</age>
    <workclass>Private</workclass>
    <education>HS-grad</education>
    <marital-status>single</marital-status>
    <sex>F</sex>
    <hours-per-week>40</hours-per-week>
    <class>N</class>
</candidat>

<candidat id="54">
    <age>33</age>
    <workclass>Private</workclass>
    <education>Bachelors</education>
    <marital-status>single</marital-status>
    <sex>F</sex>
    <hours-per-week>40</hours-per-week>
    <class>N</class>
</candidat>

<candidat id="55">
    <age>21</age>
    <workclass>Private</workclass>
    <education>HS-grad</education>
    <marital-status>single</marital-status>
    <sex>M</sex>
    <hours-per-week>35</hours-per-week>
    <class>N</class>
</candidat>

<candidat id="56">
    <age>52</age>
    <education>HS-grad</education>
    <marital-status>divorced</marital-status>
    <sex>M</sex>
    <hours-per-week>45</hours-per-week>
    <class>Y</class>
</candidat>

<candidat id="57">
    <age>48</age>
    <workclass>Private</workclass>
    <education>HS-grad</education>
    <marital-status>married</marital-status>
    <sex>M</sex>
    <hours-per-week>46</hours-per-week>
    <class>N</class>
</candidat>

<candidat id="58">
    <age>23</age>
    <workclass>Private</workclass>
    <education>Bachelors</education>
    <marital-status>single</marital-status>
    <sex>M</sex>
    <hours-per-week>40</hours-per-week>
    <class>N</class>
</candidat>

<candidat id="59">
    <age>71</age>
    <workclass>Self-emp-not-inc</workclass>
    <education>Some-college</education>
    <marital-status>divorced</marital-status>
    <sex>M</sex>
    <hours-per-week>2</hours-per-week>
    <class>N</class>
</candidat>

<candidat id="60">
    <age>29</age>
    <workclass>Private</workclass>
    <education>HS-grad</education>
    <marital-status>divorced</marital-status>
    <sex>M</sex>
    <hours-per-week>60</hours-per-week>
    <class>N</class>
</candidat>

<candidat id="61">
    <age>42</age>
    <workclass>Private</workclass>
    <education>Bachelors</education>
    <marital-status>divorced</marital-status>
    <sex>M</sex>
    <hours-per-week>50</hours-per-week>
    <class>N</class>
</candidat>

<candidat id="62">
    <age>68</age>
    <education>1st-4th</education>
    <marital-status>divorced</marital-status>
    <sex>F</sex>
    <hours-per-week>20</hours-per-week>
    <class>N</class>
</candidat>

<candidat id="63">
    <age>25</age>
    <workclass>Private</workclass>
    <education>HS-grad</education>
    <marital-status>single</marital-status>
    <sex>F</sex>
    <hours-per-week>40</hours-per-week>
    <class>N</class>
</candidat>

<candidat id="64">
    <age>44</age>
    <workclass>Self-emp-inc</workclass>
    <education>Masters</education>
    <marital-status>divorced</marital-status>
    <sex>F</sex>
    <hours-per-week>40</hours-per-week>
    <class>N</class>
</candidat>

<candidat id="65">
    <age>28</age>
    <workclass>Private</workclass>
    <education>HS-grad</education>
    <marital-status>single</marital-status>
    <sex>F</sex>
    <hours-per-week>40</hours-per-week>
    <class>N</class>
</candidat>

<candidat id="66">
    <age>45</age>
    <workclass>Self-emp-not-inc</workclass>
    <education>Masters</education>
    <marital-status>married</marital-status>
    <sex>M</sex>
    <hours-per-week>40</hours-per-week>
    <class>Y</class>
</candidat>

<candidat id="67">
    <age>36</age>
    <workclass>Private</workclass>
    <education>Some-college</education>
    <marital-status>divorced</marital-status>
    <sex>F</sex>
    <hours-per-week>40</hours-per-week>
    <class>N</class>
</candidat>

<candidat id="68">
    <age>39</age>
    <workclass>Federal-gov</workclass>
    <education>Assoc-acdm</education>
    <marital-status>single</marital-status>
    <sex>M</sex>
    <hours-per-week>42</hours-per-week>
    <class>N</class>
</candidat>

<candidat id="69">
    <age>46</age>
    <workclass>State-gov</workclass>
    <education>Masters</education>
    <marital-status>widowed</marital-status>
    <sex>M</sex>
    <hours-per-week>40</hours-per-week>
    <class>N</class>
</candidat>

<candidat id="70">
    <age>18</age>
    <workclass>Private</workclass>
    <education>11th</education>
    <marital-status>single</marital-status>
    <sex>M</sex>
    <hours-per-week>16</hours-per-week>
    <class>N</class>
</candidat>

<candidat id="71">
    <age>66</age>
    <workclass>Local-gov</workclass>
    <education>Assoc-voc</education>
    <marital-status>widowed</marital-status>
    <sex>F</sex>
    <hours-per-week>20</hours-per-week>
    <class>N</class>
</candidat>

<candidat id="72">
    <age>27</age>
    <workclass>Private</workclass>
    <education>HS-grad</education>
    <marital-status>single</marital-status>
    <sex>M</sex>
    <hours-per-week>40</hours-per-week>
    <class>N</class>
</candidat>

<candidat id="73">
    <age>28</age>
    <workclass>State-gov</workclass>
    <education>HS-grad</education>
    <marital-status>married</marital-status>
    <sex>M</sex>
    <hours-per-week>40</hours-per-week>
    <class>N</class>
</candidat>

<candidat id="74">
    <age>51</age>
    <workclass>Private</workclass>
    <education>Some-college</education>
    <marital-status>married</marital-status>
    <sex>M</sex>
    <hours-per-week>40</hours-per-week>
    <class>Y</class>
</candidat>

<candidat id="75">
    <age>27</age>
    <workclass>Private</workclass>
    <education>Bachelors</education>
    <marital-status>single</marital-status>
    <sex>M</sex>
    <hours-per-week>50</hours-per-week>
    <class>N</class>
</candidat>

<candidat id="76">
    <age>28</age>
    <workclass>State-gov</workclass>
    <education>Bachelors</education>
    <marital-status>married</marital-status>
    <sex>M</sex>
    <hours-per-week>40</hours-per-week>
    <class>Y</class>
</candidat>

<candidat id="77">
    <age>27</age>
    <workclass>Private</workclass>
    <education>HS-grad</education>
    <marital-status>married</marital-status>
    <sex>F</sex>
    <hours-per-week>25</hours-per-week>
    <class>N</class>
</candidat>

<candidat id="78">
    <age>21</age>
    <workclass>Private</workclass>
    <education>HS-grad</education>
    <marital-status>single</marital-status>
    <sex>M</sex>
    <hours-per-week>40</hours-per-week>
    <class>N</class>
</candidat>

<candidat id="79">
    <age>34</age>
    <workclass>Private</workclass>
    <education>HS-grad</education>
    <marital-status>single</marital-status>
    <sex>M</sex>
    <hours-per-week>40</hours-per-week>
    <class>N</class>
</candidat>

<candidat id="80">
    <age>18</age>
    <workclass>Private</workclass>
    <education>HS-grad</education>
    <marital-status>single</marital-status>
    <sex>M</sex>
    <hours-per-week>12</hours-per-week>
    <class>N</class>
</candidat>

<candidat id="81">
    <age>33</age>
    <workclass>Private</workclass>
    <education>Bachelors</education>
    <marital-status>married</marital-status>
    <sex>M</sex>
    <hours-per-week>65</hours-per-week>
    <class>N</class>
</candidat>

<candidat id="82">
    <age>44</age>
    <workclass>Local-gov</workclass>
    <education>Some-college</education>
    <marital-status>married</marital-status>
    <sex>M</sex>
    <hours-per-week>38</hours-per-week>
    <class>Y</class>
</candidat>

<candidat id="83">
    <age>43</age>
    <workclass>Private</workclass>
    <education>Some-college</education>
    <marital-status>divorced</marital-status>
    <sex>F</sex>
    <hours-per-week>40</hours-per-week>
    <class>N</class>
</candidat>

<candidat id="84">
    <age>30</age>
    <workclass>Private</workclass>
    <education>Some-college</education>
    <marital-status>single</marital-status>
    <sex>M</sex>
    <hours-per-week>45</hours-per-week>
    <class>N</class>
</candidat>

<candidat id="85">
    <age>40</age>
    <workclass>Private</workclass>
    <education>7th-8th</education>
    <marital-status>married</marital-status>
    <sex>M</sex>
    <hours-per-week>40</hours-per-week>
    <class>Y</class>
</candidat>

<candidat id="86">
    <age>37</age>
    <workclass>Federal-gov</workclass>
    <education>Some-college</education>
    <marital-status>married</marital-status>
    <sex>M</sex>
    <hours-per-week>42</hours-per-week>
    <class>Y</class>
</candidat>

<candidat id="87">
    <age>34</age>
    <workclass>Private</workclass>
    <education>HS-grad</education>
    <marital-status>married</marital-status>
    <sex>M</sex>
    <hours-per-week>40</hours-per-week>
    <class>N</class>
</candidat>

<candidat id="88">
    <age>41</age>
    <workclass>Self-emp-not-inc</workclass>
    <education>Bachelors</education>
    <marital-status>divorced</marital-status>
    <sex>F</sex>
    <hours-per-week>40</hours-per-week>
    <class>N</class>
</candidat>

<candidat id="89">
    <age>53</age>
    <education>Bachelors</education>
    <marital-status>divorced</marital-status>
    <sex>F</sex>
    <hours-per-week>50</hours-per-week>
    <class>N</class>
</candidat>

<candidat id="90">
    <age>31</age>
    <workclass>Private</workclass>
    <education>Masters</education>
    <marital-status>married</marital-status>
    <sex>F</sex>
    <hours-per-week>50</hours-per-week>
    <class>N</class>
</candidat>

<candidat id="91">
    <age>58</age>
    <workclass>State-gov</workclass>
    <education>Doctorate</education>
    <marital-status>married</marital-status>
    <sex>M</sex>
    <hours-per-week>1</hours-per-week>
    <class>Y</class>
</candidat>

<candidat id="98">
    <age>36</age>
    <workclass>Private</workclass>
    <education>Some-college</education>
    <marital-status>divorced</marital-status>
    <sex>M</sex>
